version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQLDB_DATABASE}
      MYSQL_USER: ${MYSQLDB_USER}
      MYSQL_PASSWORD: ${MYSQLDB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - pollgenerator-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/${MYSQLDB_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQLDB_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQLDB_PASSWORD}
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - db
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "db", "-u", "${MYSQLDB_USER}", "-p${MYSQLDB_PASSWORD}" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "8080:8080"
    networks:
      - pollgenerator-network

networks:
  pollgenerator-network:

volumes:
  db-data: